### ISSUE TITLE
Error: Spline64 is not a supported kernel

### ISSUE THREAD

**Issue by motbob** [Infiziert90/getnative#12]
```
getnative -k spline16 -pf png -min 700 -max 1000 "C:\Users\motbob\Desktop\00000.m2ts_snapshot_08.38.188.png"
Traceback (most recent call last):
  File "C:\Program Files\Python38\Scripts\getnative-script.py", line 11, in <module>
    load_entry_point('getnative==2.2.0', 'console_scripts', 'getnative')()
  File "C:\Program Files\Python38\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Program Files\Python38\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "C:\Program Files\Python38\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "C:\Program Files\Python38\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Program Files\Python38\lib\site-packages\getnative-2.2.0-py3.8.egg\getnative\app.py", line 105, in <module>
  File "C:\Program Files\Python38\lib\site-packages\getnative-2.2.0-py3.8.egg\getnative\app.py", line 54, in __init__
  File "C:\Program Files\Python38\lib\site-packages\getnative-2.2.0-py3.8.egg\getnative\app.py", line 67, in check_input
getnative.utils.GetnativeException: descale: spline64 is not a supported kernel.
Done.
```

I get the same error even with a minimal command line, e.g. `getnative  "C:\Users\motbob\Desktop\00000.m2ts_snapshot_08.38.188.png"`

All dependencies seem to be updated; Vapoursynth version is 50

**Comment by Infiziert90** [comment]
> descale: spline64 is not a supported kernel.

> -k spline16

Okay? That seems super weird, but i can't reproduce it ...

**Comment by Kiyamou** [comment]
It's related to the version of descale. Irrational-Encoding-Wizardry/vapoursynth-descale before r3 and BluBb-mADe/vapoursynth-descale doesn't all support spline64.

**Comment by Infiziert90** [comment]
> It's related to the version of descale. Irrational-Encoding-Wizardry/vapoursynth-descale before r3 and BluBb-mADe/vapoursynth-descale doesn't all support spline64.

That's correct... And the error 
I will fix it later, so that older versions drop out with correct error

**Comment by motbob** [comment]
That's not the issue. My descale.py supports spline64.

**Comment by Infiziert90** [comment]
Spline64!=Despline64

It looks like the descale version (c Plugin not .py) is not supporting Despline64. 

Pls open vsedit and try executing something like this
```
import vapoursynth 
core = vapoursynth.core

core.descale.Despline64()
........ 
```

**Comment by motbob** [comment]
OK, yes, that was the problem. I had an old dll.

Apologies. Thank you for being patient with me.
